"""tscfbench: turn before/after time-series questions into counterfactual charts, reproducible reports, and agent-ready handoffs."""

__version__ = "1.8.0"

from .agent import (
    AgentResearchTaskSpec,
    PanelAgentBundle,
    RuntimeProfile,
    TSCFBenchMCPServer,
    TokenBudget,
    build_context_plan,
    build_panel_agent_bundle,
    build_repo_map_text,
    export_openai_function_tools,
    list_tool_profiles,
    export_runtime_profile,
    invoke_tool,
    list_runtime_profiles,
    render_agents_md,
    render_local_tscfbench_mcp_config,
)
from .bench import BenchmarkOutput, benchmark
from .canonical import (
    CanonicalBenchmarkSpec,
    canonical_install_notes,
    list_canonical_studies,
    make_canonical_sweep_spec,
    render_canonical_markdown,
    run_canonical_benchmark,
)
from .core import ImpactCase, PanelCase, PredictionResult
from .datasets import (
    DatasetCard,
    get_dataset_card,
    has_snapshot,
    list_dataset_cards,
    load_basque_country,
    load_california_prop99,
    load_german_reunification,
    load_named_dataset,
    load_coingecko_market_chart,
    load_csv_like_price_series,
    load_fred_series,
    load_github_star_history,
    make_event_impact_case,
    snapshot_path,
    to_log_returns,
)
from .experiments import ImpactExperimentSpec, PanelExperimentSpec, run_panel_experiment
from .guidebook import (
    benchmark_cards,
    recommend_start_path,
    render_benchmark_cards_markdown,
    render_start_here_markdown,
    render_workflow_recipes_markdown,
    workflow_recipes,
)
from .install_matrix import InstallMatrixRow, install_matrix, render_install_matrix_markdown
from .integrations import adapter_catalog, get_adapter_card, recommend_adapter_stack
from .narrative import (
    api_atlas,
    capability_map,
    package_story,
    render_api_atlas_markdown,
    render_capability_map_markdown,
    render_package_story_markdown,
    render_scenario_matrix_markdown,
    render_tutorial_index_markdown,
    scenario_matrix,
    tutorial_index,
    write_release_kit,
)
from .product import (
    api_handbook,
    cli_guide,
    environment_profiles,
    package_overview,
    render_api_handbook_markdown,
    render_cli_guide_markdown,
    render_environment_profiles_markdown,
    render_package_overview_markdown,
    render_use_cases_markdown,
    use_case_catalog,
)
from .protocols import PanelBenchmarkOutput, PanelProtocolConfig, benchmark_panel
from .report import render_panel_markdown
from .showcases import (
    high_traffic_cases,
    public_data_sources,
    render_high_traffic_cases_markdown,
    render_public_data_sources_markdown,
)
from .onramp import (
    doctor_report,
    essential_commands,
    render_doctor_markdown,
    render_essential_commands_markdown,
    render_feedback_response_markdown,
    render_tool_profiles_markdown,
    run_quickstart,
    tool_profile_notes,
)

from .demo_cases import (
    beginner_examples,
    demo_catalog,
    demo_data_path,
    get_demo_case,
    render_demo_gallery_markdown,
    run_demo,
)
from .csv_runner import run_csv_impact, run_csv_panel
from .visuals import write_impact_visual_bundle, write_panel_visual_bundle
from .share_packages import make_share_package_for_demo, make_share_package_from_run
from .positioning import (
    ecosystem_audit,
    feature_coverage_matrix,
    package_differentiators,
    render_agent_first_design_markdown,
    render_differentiators_markdown,
    render_docs_homepage_markdown,
    render_ecosystem_audit_markdown,
    render_feature_coverage_markdown,
    render_github_readme_markdown,
    write_positioning_assets,
)
from .study import ResearchStudyBlueprint, build_research_study_blueprint
from .sweeps import SweepMatrixSpec, make_default_sweep_spec, render_sweep_markdown, run_sweep

__all__ = [
    "__version__",
    "ImpactCase",
    "PanelCase",
    "PredictionResult",
    "benchmark",
    "BenchmarkOutput",
    "PanelProtocolConfig",
    "PanelBenchmarkOutput",
    "benchmark_panel",
    "PanelExperimentSpec",
    "ImpactExperimentSpec",
    "run_panel_experiment",
    "AgentResearchTaskSpec",
    "TokenBudget",
    "PanelAgentBundle",
    "build_panel_agent_bundle",
    "build_context_plan",
    "build_repo_map_text",
    "export_openai_function_tools",
    "list_tool_profiles",
    "export_runtime_profile",
    "list_runtime_profiles",
    "RuntimeProfile",
    "invoke_tool",
    "TSCFBenchMCPServer",
    "render_agents_md",
    "render_local_tscfbench_mcp_config",
    "adapter_catalog",
    "get_adapter_card",
    "recommend_adapter_stack",
    "SweepMatrixSpec",
    "make_default_sweep_spec",
    "run_sweep",
    "render_sweep_markdown",
    "ResearchStudyBlueprint",
    "build_research_study_blueprint",
    "InstallMatrixRow",
    "install_matrix",
    "render_install_matrix_markdown",
    "CanonicalBenchmarkSpec",
    "list_canonical_studies",
    "make_canonical_sweep_spec",
    "run_canonical_benchmark",
    "render_canonical_markdown",
    "canonical_install_notes",
    "DatasetCard",
    "get_dataset_card",
    "list_dataset_cards",
    "load_named_dataset",
    "load_german_reunification",
    "load_california_prop99",
    "load_basque_country",
    "has_snapshot",
    "snapshot_path",
    "load_github_star_history",
    "load_coingecko_market_chart",
    "load_fred_series",
    "load_csv_like_price_series",
    "to_log_returns",
    "make_event_impact_case",
    "package_overview",
    "api_handbook",
    "use_case_catalog",
    "environment_profiles",
    "cli_guide",
    "render_package_overview_markdown",
    "render_api_handbook_markdown",
    "render_use_cases_markdown",
    "render_environment_profiles_markdown",
    "render_cli_guide_markdown",
    "benchmark_cards",
    "workflow_recipes",
    "recommend_start_path",
    "render_benchmark_cards_markdown",
    "render_start_here_markdown",
    "render_workflow_recipes_markdown",
    "package_story",
    "capability_map",
    "scenario_matrix",
    "tutorial_index",
    "api_atlas",
    "render_package_story_markdown",
    "render_capability_map_markdown",
    "render_scenario_matrix_markdown",
    "render_tutorial_index_markdown",
    "render_api_atlas_markdown",
    "write_release_kit",
    "high_traffic_cases",
    "public_data_sources",
    "render_high_traffic_cases_markdown",
    "render_public_data_sources_markdown",

    "beginner_examples",
    "demo_catalog",
    "demo_data_path",
    "get_demo_case",
    "render_demo_gallery_markdown",
    "run_demo",
    "run_csv_impact",
    "run_csv_panel",
    "write_impact_visual_bundle",
    "write_panel_visual_bundle",
    "make_share_package_for_demo",
    "make_share_package_from_run",
    "doctor_report",
    "essential_commands",
    "render_doctor_markdown",
    "render_essential_commands_markdown",
    "render_feedback_response_markdown",
    "render_tool_profiles_markdown",
    "run_quickstart",
    "tool_profile_notes",
    "ecosystem_audit",
    "feature_coverage_matrix",
    "package_differentiators",
    "render_ecosystem_audit_markdown",
    "render_feature_coverage_markdown",
    "render_differentiators_markdown",
    "render_github_readme_markdown",
    "render_docs_homepage_markdown",
    "render_agent_first_design_markdown",
    "write_positioning_assets",
    "render_panel_markdown",
]
