from __future__ import annotations

import json
import math
import shutil
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping

from tscfbench.demo_cases import get_demo_case, run_demo


def _first_existing(payload: Mapping[str, str], keys: Iterable[str]) -> str | None:
    for key in keys:
        value = payload.get(key)
        if value and Path(value).exists():
            return str(value)
    return None


def _copy_if_exists(src: str | None, dst: Path) -> str | None:
    if not src:
        return None
    source = Path(src)
    if not source.exists():
        return None
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, dst)
    return str(dst)


def _demo_citation_block(demo_id: str, dataset_file: str) -> str:
    return "\n".join(
        [
            "Suggested citation block",
            "",
            "Software: tscfbench v1.8.0",
            f"Demo case: {demo_id}",
            f"Bundled dataset: {dataset_file}",
            "Method note: Counterfactual chart and report generated under a reproducible tscfbench demo spec.",
        ]
    )


def _clean_scalar(value: Any) -> Any:
    if value is None:
        return None
    try:
        scalar = value.item() if hasattr(value, "item") else value
    except Exception:  # noqa: BLE001
        scalar = value
    if isinstance(scalar, float) and (not math.isfinite(scalar)):
        return None
    return scalar


def _clean_summary(summary: Mapping[str, Any] | None) -> Dict[str, Any]:
    clean: Dict[str, Any] = {}
    for key, value in (summary or {}).items():
        scalar = _clean_scalar(value)
        if scalar is None:
            continue
        clean[key] = scalar
    return clean


def _format_metric(value: Any, *, digits: int = 2, signed: bool = False) -> str:
    scalar = _clean_scalar(value)
    if scalar is None:
        return "n/a"
    if isinstance(scalar, int):
        return f"{scalar:+d}" if signed else str(scalar)
    if isinstance(scalar, float):
        return f"{scalar:+.{digits}f}" if signed else f"{scalar:.{digits}f}"
    return str(scalar)


def _headline_result(summary: Mapping[str, Any]) -> str:
    if "post_pre_rmspe_ratio" in summary:
        ratio = _format_metric(summary.get("post_pre_rmspe_ratio"), digits=2)
        cum = _format_metric(summary.get("cum_effect"), digits=1, signed=True)
        treated = summary.get("treated_unit", "treated unit")
        return f"Estimated cumulative effect for {treated}: {cum}; post/pre RMSPE ratio: {ratio}."
    post_points = summary.get("post_period_points")
    cum = summary.get("cum_effect")
    avg = summary.get("avg_effect")
    controls = summary.get("controls")
    bits = []
    if cum is not None and post_points is not None:
        bits.append(f"Estimated cumulative effect: {_format_metric(cum, digits=1, signed=True)} over {int(post_points)} post-event points")
    elif cum is not None:
        bits.append(f"Estimated cumulative effect: {_format_metric(cum, digits=1, signed=True)}")
    if avg is not None:
        bits.append(f"average post-period effect: {_format_metric(avg, digits=2, signed=True)}")
    if controls is not None:
        bits.append(f"controls: {controls}")
    if not bits:
        return "The share package captures the observed series, its counterfactual path, and the main post-event deviation in a compact form."
    return "; ".join(bits) + "."


def _social_caption(title: str, summary: Mapping[str, Any]) -> str:
    headline = _headline_result(summary)
    return f"{title}: {headline} Counterfactual chart, report, and share assets generated by tscfbench."


def make_share_package_from_run(
    *,
    demo_id: str,
    title: str,
    question: str,
    takeaway: str,
    generated_files: Mapping[str, str],
    output_dir: str | Path,
    run_summary: Mapping[str, Any] | None = None,
) -> Dict[str, Any]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    clean_summary = _clean_summary(run_summary)

    paths: Dict[str, str | None] = {}
    paths["report_md"] = _copy_if_exists(generated_files.get("report_md"), out / "report.md")
    paths["metrics_json"] = _copy_if_exists(generated_files.get("metrics_json"), out / "metrics.json")
    paths["prediction_csv"] = _copy_if_exists(generated_files.get("prediction_csv"), out / "prediction_frame.csv")
    paths["treated_vs_counterfactual"] = _copy_if_exists(
        _first_existing(generated_files, ["treated_vs_counterfactual_png", "treated_vs_counterfactual_svg"]),
        out / ("treated_vs_counterfactual.png" if generated_files.get("treated_vs_counterfactual_png") else "treated_vs_counterfactual.svg"),
    )
    paths["point_effect"] = _copy_if_exists(
        _first_existing(generated_files, ["point_effect_png", "point_effect_svg"]),
        out / ("point_effect.png" if generated_files.get("point_effect_png") else "point_effect.svg"),
    )
    paths["cumulative_impact"] = _copy_if_exists(
        _first_existing(generated_files, ["cumulative_impact_png", "cumulative_impact_svg"]),
        out / ("cumulative_impact.png" if generated_files.get("cumulative_impact_png") else "cumulative_impact.svg"),
    )
    donor_src = _first_existing(generated_files, ["donor_contributions_png", "donor_contributions_svg"])
    if donor_src:
        donor_ext = ".png" if donor_src.endswith(".png") else ".svg"
        paths["donor_contributions"] = _copy_if_exists(donor_src, out / f"donor_contributions{donor_ext}")
    else:
        paths["donor_contributions"] = None
    paths["share_card"] = _copy_if_exists(
        _first_existing(generated_files, ["share_card_png", "share_card_svg"]),
        out / ("share_card.png" if generated_files.get("share_card_png") else "share_card.svg"),
    )

    summary_payload = {
        "demo_id": demo_id,
        "title": title,
        "question": question,
        "takeaway": takeaway,
        "summary_metrics": clean_summary,
        "headline_result": _headline_result(clean_summary),
        "social_caption": _social_caption(title, clean_summary),
    }
    summary_json = out / "summary.json"
    summary_json.write_text(json.dumps(summary_payload, indent=2, ensure_ascii=False, default=str), encoding="utf-8")

    summary_md = out / "SUMMARY.md"
    metric_lines = [f"- {k}: {v}" for k, v in clean_summary.items()] or ["- summary_metrics: none available"]
    summary_md.write_text(
        "\n".join(
            [
                f"# {title}",
                "",
                question,
                "",
                f"This share package includes a counterfactual chart, a reproducible report, and a compact handoff bundle for the named demo `{demo_id}`.",
                f"Main takeaway: {takeaway}",
                "",
                "## Headline result",
                "",
                _headline_result(clean_summary),
                "",
                "## Summary metrics",
                "",
                *metric_lines,
                "",
                "## Two-sentence summary",
                "",
                f"`{title}` turns a before/after time-series question into a counterfactual chart and a reproducible report.",
                _headline_result(clean_summary),
                "",
                "## Suggested social caption",
                "",
                _social_caption(title, clean_summary),
            ]
        ),
        encoding="utf-8",
    )
    citation_txt = out / "CITATION.txt"
    citation_txt.write_text(_demo_citation_block(demo_id, f"demo_{demo_id.replace('-', '_')}.csv"), encoding="utf-8")

    manifest = {
        "kind": "share_package",
        "demo_id": demo_id,
        "title": title,
        "question": question,
        "takeaway": takeaway,
        "summary_metrics": clean_summary,
        "headline_result": _headline_result(clean_summary),
        "files": {k: v for k, v in paths.items() if v},
        "summary_path": str(summary_md),
        "summary_json_path": str(summary_json),
        "citation_path": str(citation_txt),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return manifest


def make_share_package_for_demo(
    demo_id: str,
    *,
    output_dir: str | Path = "tscfbench_share_package",
    plot: bool = True,
) -> Dict[str, Any]:
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    demo_case = get_demo_case(demo_id)
    raw_dir = root / "run_artifacts"
    demo_run = run_demo(demo_id, output_dir=raw_dir, plot=plot)
    clean_summary = _clean_summary(demo_run.get("summary", {}))
    share_dir = root / f"{demo_case.id}_share_package"
    share = make_share_package_from_run(
        demo_id=demo_case.id,
        title=demo_case.title,
        question=demo_case.question,
        takeaway=demo_case.takeaway,
        generated_files=demo_run["generated_files"],
        output_dir=share_dir,
        run_summary=clean_summary,
    )
    return {
        "kind": "demo_share_package",
        "demo_id": demo_case.id,
        "output_dir": str(root),
        "share_package_dir": str(share_dir),
        "run_output_dir": str(Path(demo_run["output_dir"])),
        "summary": clean_summary,
        "generated_files": demo_run.get("generated_files", {}),
        "share_manifest": share,
        "next_command": "python -m tscfbench demo-gallery",
    }


__all__ = ["make_share_package_for_demo", "make_share_package_from_run"]
